name: Run linter and tests on push
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-linters-and-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Run build
        run: npm run build
