name: Run linter and tests on push
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-linters-and-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: see variables
        run: echo "$CLERK_SECRET_KEY $LIVEBLOCKS_SECRET_KEY $NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY"
      - name: Run build
        env : 
          CLERK_SECRET_KEY : ${{ secrets.CLERK_SECRET_KEY }}
          LIVEBLOCKS_SECRET_KEY : ${{ secrets.LIVEBLOCKS_SECRET_KEY }} }}
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY : ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }} }}
        run: npm run build
